# Site settings
title: Clay Karwisch
description: Clay Karwisch Portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Clay Karwisch
user_description: I am a software engineer based in Athens, Georgia with experience building backend and frontend systems. I have a deep understanding of the fundamentals of object oriented programming, networking, and relational databases. I am especially interested in writing clean, maintainable code and understanding the tradeoffs involved in choosing a technology stack to solve a particular problem.
user_title: Software Engineer
email: clay.karwisch@gmail.com
# twitter_username: lorem_ipsum
github_username:  cwkarwisch
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
