# Site settings
title: Travis Lee Holt
description: trvslhlt portfolio
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Travis Lee Holt
user_description: I'm a Software Engineer based in Brooklyn, NY. You got rocks? I'll climb em.
user_title: Software Engineer
email: trvslhlt@gmail.com
# twitter_username: lorem_ipsum
github_username:  trvslhtl
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
